### PR TITLE
Updated halloffame.yml

### PR DESCRIPTION
**Pull request by bjoreman**
Updated my entry to be x2 and August. Oops, I did it again …

### CODE REVIEW

**Comment by kevquirk** [comment]
There's no need to delete the first instance of you completing the challenge. Hyde Stevenson has done it a couple of times too, and I kept his in. I think it's important to keep every instance of you completing the challenge in there.

Can you edit the PR to re-add the first instance of you completing it please?

Congrats on doing it again...you lunatic!

**Comment by bjoreman** [comment]
Haha, more than fair enough! I’ll update!

(And also look at my GH notification settings, I missed your response completely.)

**Comment by bjoreman** [comment]
There we go, adjusted.

**Comment by kevquirk** [comment]
Thanks and congrats on doing it twice...that's prolific!

**Pull request merged**
